#!/bin/bash
set -vx
set -euo pipefail
file $(which $CC)
uname -a
rm -f hello
$CC -o hello hello.c
if [ "$(./hello)" = "Hello world!" ]; then echo "successful"; exit 0; else echo "unsuccessful"; exit 1; fi
