#!/bin/bash

if [[ "x$CC" == x ]]; then
  CC=cc
fi

#file $(which $CC)
uname -a
rm -f hello
$CC -o hello hello.c
if [ "$(./hello)" = "Hello world! - Sud" ]; then echo "successful - Sud"; exit 0; else echo "unsuccessful- Sud"; exit 1; fi
